twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/as_tailwind_2_layout.html.twig'
    globals:
        supported_locales: '%app.supported_locales%'
        escaped_default_share_text: '%escaped_default_share_text%'
        globals_website_title_suffix: '%globals_website_title_suffix%'
        globals_website_url: '%globals_website_url%'
        globals_website_name: '%globals_website_name%'
        globals_website_subtitle: '%globals_website_subtitle%'
        globals_website_description: '%globals_website_description%'
        globals_facebook_app_id: '%globals_facebook_app_id%'
        user_photos_http_path: '%user_photos_http_path%'
        user_pictures_directory: '%user_pictures_directory%'
        website_title: 'Aeonshift Points Calculator'
    paths:
        'assets/images': images
when@test:
    twig:
        strict_variables: true
