workers:
    # Remove the temp file for Windows users, sometimes the server crashes and this needs to be deleted
    # delete:
    #     cmd: ['cmd.exe', '/C', 'del /F /S /Q C:\Users\[Your User]\.symfony5\var']
    # Enable Tailwind everytime we start the Symfony server
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', '--poll']
