locale_redirect:
    path: /
    controller: \App\Controller\IndexController::index

# Localized controllers
controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%app.default_locale%'
    requirements:
        _locale: '%app.supported_locales_route_requirement%'
    exclude:
        - '../src/Controller/API/*'

# API controllers — no locale
api_controllers:
    resource: '../src/Controller/API/*'
    type: attribute
    prefix: /api
