parameters:
    app.default_locale: 'en'
    app.table_prefix: 'as_'
    app.supported_locales: ['en', 'fr']
    app.supported_locales_route_requirement: 'en|fr'
    # ----
    escaped_default_share_text: 'Aeonshift Points Calculator - %globals_website_subtitle%'
    globals_website_subtitle: 'Automatic calculation of your Aeonshift deck points and validation'
    globals_website_title_suffix: ' | Aeonshift Points Calculator'
    globals_website_url: 'https://points.mtgdc.info'
    globals_website_name: 'Aeonshift Points Calculator'
    globals_website_description: 'Automatic calculation of your Aeonshift deck points and validation'
    globals_facebook_app_id: '160828815182734'
    # ----
    user_photos_http_path: '/uploads/users/pictures/'
    user_pictures_directory: '%kernel.project_dir%/public%user_photos_http_path%'
    # ----
    scryfall.bulk_api_url: 'https://api.scryfall.com/bulk-data'
    scryfall.cards_source_dir: 'cardsources/scryfall/defaultcards'
    scryfall.bulk_data_type: 'default_cards'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $scryfallBulkApiUrl: '%scryfall.bulk_api_url%'
            $cardsSourceDir: '%scryfall.cards_source_dir%'
            $bulkDataType: '%scryfall.bulk_data_type%'
            $tablePrefix: '%app.table_prefix%'


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    doctrine.table.prefix:
        arguments:
            $prefix: '%app.table_prefix%'
        class: App\EventListener\DoctrineTablePrefixListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, method: loadClassMetadata }
