##############################################################
######################## AeonShift CI ########################
##############################################################
name: AeonShift Github CI - Static Calculator Build App

# We don't create releases nor uses Git tags in this project,
# so we just use 'latest' as a static tag for the release action.
# This way, the latest build is always available under the 'latest' release.
# As the application is always "perpetual" as a versioned state.
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_ENV: github

jobs:
    ##############################################################
    ################ Static Calculator App Build #################
    ##############################################################
    static_build:
        name: AeonShift Github CI - Static Calculator Build App
        runs-on: ubuntu-latest

        steps:
            # ---- Checkout Repository ----
            -   name: Checkout repository
                uses: actions/checkout@v4

            # ---- Node Setup ----
            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 24

            # ---- Build Symfony assets & Twig output ----
            -   name: Install PHP / Composer
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'

            # -- Install Composer dependencies ----
            -   name: Install Composer deps
                run: composer install --no-interaction

            # ---- Warm up Symfony caches ----
            -   name: Warm Symfony cache for env Dev
                run: php bin/console cache:warmup --env=dev -vvv --no-optional-warmers

            -   name: Warm Symfony cache for env Github
                run: php bin/console cache:warmup --env=github -vvv --no-optional-warmers

            # ---- Render Twig template to an output directory ----
            -   name: Render Twig output
                run: php bin/console aeonshift:mtg:builder:staticassets

            # ---- Install JS dependencies (importmap must be dumped beforehand) ----
            -   name: Install JS deps for Importmap
                run: |
                    npm install -g esbuild
                    php bin/console importmap:dump

            # ---- Upload artifacts to GitHub Release ----
            -   name: Create/Update Release and Upload Assets
                uses: softprops/action-gh-release@v2
                with:
                    tag_name: latest
                    name: "Latest AeonShift Points Calculator Static Build"
                    files: |
                        public/static-calculators/mtg/aeonshift-mtg-calculator.html
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
