##############################################################
######################## AeonShift CI ########################
##############################################################
name: AeonShift Github CI - PHP-CS-Fixer Check
description: |
    This workflow runs PHP-CS-Fixer to ensure code style consistency.
branding:
    icon: 'align-justify'
    color: 'white'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_ENV: github

jobs:
    ##############################################################
    ##################### PHP-CS-Fixer Check #####################
    ##############################################################
    php_quality:
        name: AeonShift Github CI - PHP-CS-Fixer Check
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            # ---- PHP Setup ----
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    extensions: mbstring, intl, pdo_mysql
                    coverage: none

            # -- Install Composer dependencies ----
            -   name: Install Composer dependencies
                run: composer install --no-interaction --prefer-dist --no-scripts

            # ---- Warm up Symfony caches ----
            -   name: Warm Symfony cache for env Dev
                run: php bin/console cache:warmup --env=dev -vvv --no-optional-warmers

            -   name: Warm Symfony cache for env Github
                run: php bin/console cache:warmup --env=github -vvv --no-optional-warmers

            # ---- PHP-CS-Fixer ----
            -   name: Run PHP-CS-Fixer Using Embedded Configuration
                run: vendor/bin/php-cs-fixer check -n -vvv --show-progress=none
