##############################################################
######################## AeonShift CI ########################
##############################################################
name: AeonShift Github CI - PHPUnit Tests
description: |
    This workflow runs PHPStan (maximum level) to perform static analysis
    on the PHP codebase to ensure code quality and catch potential issues.
branding:
    icon: 'target'
    color: 'white'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_ENV: test

jobs:
    ##############################################################
    ####################### PHPUnit Tests ########################
    ##############################################################
    php_quality:
        name: AeonShift Github CI - PHPUnit Tests
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            # ---- PHP Setup ----
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    extensions: mbstring, intl, pdo_mysql
                    coverage: none

            # -- Install Composer dependencies ----
            -   name: Install Composer dependencies
                run: composer install --no-interaction --prefer-dist --no-scripts

            # ---- Warm up Symfony caches ----
            -   name: Warm Symfony cache for env Test
                run: php bin/console cache:warmup --env=test -vvv --no-optional-warmers

            # ---- PHPUnit ----
            -   name: Run PHPUnit Using Embedded Configuration
                run: vendor/bin/phpunit --colors=always
